-- MySQL Script generated by MySQL Workbench
-- Fri Sep 18 20:56:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DONO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DONO` (
  `Nome` VARCHAR(50) NOT NULL,
  `RG` INT NOT NULL,
  `Endereco` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`RG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Animal` (
  `ID` INT NOT NULL,
  `Raca` VARCHAR(50) NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `DONO_RG` INT NOT NULL,
  PRIMARY KEY (`ID`, `DONO_RG`),
  INDEX `fk_Animal_DONO_idx` (`DONO_RG` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_DONO`
    FOREIGN KEY (`DONO_RG`)
    REFERENCES `mydb`.`DONO` (`RG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
